# Generated by Django 4.1 on 2022-09-11 19:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='cep',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='CEP inválido. Exemplo: 12345-678', regex='^\\d{5}-\\d{3}$')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Telefone inválido. Formato: 99 99999-9999', regex='^\\d{2} \\d{4,5}-\\d{4}$')]),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('picture', models.ImageField(blank=True, upload_to='ticket_pictures')),
                ('password', models.CharField(blank=True, max_length=100)),
                ('validated', models.BooleanField(default=False)),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer', to='tickets.profile')),
                ('offerer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.profile')),
            ],
        ),
    ]
