# Generated by Django 4.1 on 2022-08-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0002_set_groups_and_perms"),
    ]

    operations = [
        migrations.AddField(
            model_name="offererprofile",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
