# Generated by Django 4.1 on 2022-08-17 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0004_ticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="validated",
            field=models.BooleanField(default=False),
        ),
    ]
