# Generated by Django 4.1 on 2022-10-01 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tickets.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0004_ticket_expiration_alter_ticket_buyer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offererapproval',
            name='approved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_by', to=settings.AUTH_USER_MODEL, validators=[tickets.validators.is_regulator]),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='picture',
            field=models.ImageField(blank=True, default='default_ticket.png', upload_to='ticket_pics'),
        ),
    ]
