# Generated by Django 4.1 on 2022-10-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0006_address_latitude_address_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="random_id",
            field=models.CharField(max_length=8, null=True),
        ),
    ]
