# Generated by Django 4.1 on 2022-10-03 22:42

from django.db import migrations, models
import tickets.models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0007_ticket_random_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="random_id",
            field=models.CharField(
                default=tickets.models.random_id_generator, max_length=8, null=True
            ),
        ),
    ]
